[package]
name = "sysapi"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
axum-server = "0.7.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
sysinfo = { version = "0.32.0" }
tokio = { version = "1.41.0", features = ["full"] }
lazy_static = "1.5.0"